routes/web.php
<?php

use App\Http\Controllers\BookController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SessionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');

Route::get('/about', function () {
    return view('about');
})->name('about');

Route::get('/track', function () {
    return view('track');
})->name('track');

Route::get('/cart', function () {
    return view('cart');
})->name('cart');

Route::get('/login', function () {
    return view('login');
})->name('login');

Route::get('/register', function () {
    return view('register');
})->name('register');

Route::resources([
    'users' => UserController::class,
    'books' => BookController::class,
    'orders' => OrderController::class,
    'suppliers' => SupplierController::class,
    'payments' => PaymentController::class,
]);

Route::get('user', [UserController::class, 'logout'])->name('users.logout');

resources/views/about.blade.php
@extends('master')

@section('title')
Camino Librerías - Nosotros
@endsection

@section('content')
<div class="container">
    @extends('header')
    <section class="slider">
        <img src="imagenes/aboutpage.jpg" alt="" width="100%" height="500px">
    </section>

    <section class="cuerpo">
        <h1 class="titulo">
            Sobre nosotros
        </h1>
        <p>
            Librerías Camino es una tienda de libros mexicana que cuenta con más de 50 sucursales
            en todo el país, estamos presentes en los estados más importantes de la república como
            Guadalajara, Monterrey, Aguascalientes y Ciudad de México. Brindamos servicio nacional
            las 24 horas del día los 7 días de la semana a través de nuestra tienda en línea.
            Somos la mejor tienda de libros en el país, otorgando seguridad y rapidez en la compra
            de tus libros favoritos.
        </p>

        <article class="caja-mision">
            <div class="subtitulo">
                <h3 class="servicios">Misión</h3>
            </div>
            <div class="contenido">
                Difundir la cultura y el entretenimiento
                otorgando lugares seguros y dignos para
                la distribución y venta de libros.
            </div>
        </article>

        <article class="caja-vision">
            <div class="subtitulo">
                <h3 class="servicios">Visión</h3>
            </div>
            <div class="contenido">
                Ser una empresa referente en el mercado para el que
                estamos trabajando y para las personas.
            </div>
        </article>
    </section>
    @extends('footer')
</div>
@endsection

resources/views/books.blade.php
@extends('master')

@section('title')
Camino Librerías - Libros
@endsection

@section('content')
<div class="container">
    @extends('header')

    <center>
        <form action="" class="search-form">
            <label for="search">Buscar libro:</label>
            <input type="text" name="search" id="search" class="search-bar">
            <button type="submit" class="book-button">Buscar</button>
        </form>
        @if(session('is_admin') == 1)
            <a href=""><button class="add-button">Agregar</button></a>
            <a href=""><button class="delete-button">Eliminar</button></a>
        @endif
    </center>

    <article class="book">
        <a href="">
            <img src="libros/pedroparamo.png" alt="libro pedro paramo">
        </a>
        <div class="book-info">
            <p>Pedro Páramo</p>
            <p>Juan Rulfo</p>
            <p>$85.00</p>
            <button class="book-button">
                <img src="imagenes/cart.png" alt="cart" width="24px">
                Agregar al Carrito
            </button>
        </div>
    </article>

    <article class="book">
        <a href="">
            <img src="libros/personanormal.png" alt="libro pedro paramo">
        </a>
        <div class="book-info">
            <p>Persona Normal</p>
            <p>Benito Taibo</p>
            <p>$100.00</p>
            <button class="book-button">
                <img src="imagenes/cart.png" alt="cart" width="24px">
                Agregar al Carrito
            </button>
        </div>
    </article>

    <article class="book">
        <a href="">
            <img src="libros/batallasdesierto.png" alt="libro pedro paramo">
        </a>
        <div class="book-info">
            <p>Las Batallas en el Desierto</p>
            <p>José Emilio Pacheco</p>
            <p>$85.00</p>
            <a href="cart.html"><button class="book-button">
                    <img src="imagenes/cart.png" alt="cart" width="24px">
                    Agregar al Carrito
                </button></a>
        </div>
    </article>

    <article class="book">
        <a href="">
            <img src="libros/vientodistante.png" alt="libro pedro paramo">
        </a>
        <div class="book-info">
            <p>El Viento Distante</p>
            <p>José Emilio Pacheco</p>
            <p>$85.00</p>
            <a href="cart.html"><button class="book-button">
                    <img src="imagenes/cart.png" alt="cart" width="24px">
                    Agregar al Carrito
                </button></a>
        </div>
    </article>

    <article class="book">
        <a href="">
            <img src="libros/elprincipito.png" alt="libro el principito">
        </a>
        <div class="book-info">
            <p>El Principito</p>
            <p>Antoine De Saint-Exupéry</p>
            <p>$75.00</p>
            <a href="cart.html"><button class="book-button">
                    <img src="imagenes/cart.png" alt="cart" width="24px">
                    Agregar al Carrito
                </button></a>
        </div>
    </article>

    <article class="book">
        <a href="">
            <img src="libros/readyplayerone.png" alt="libro ready player one">
        </a>
        <div class="book-info">
            <p>Ready Player One</p>
            <p>Ernest Cline</p>
            <p>$200.00</p>
            <a href="cart.html"><button class="book-button">
                    <img src="imagenes/cart.png" alt="cart" width="24px">
                    Agregar al Carrito
                </button></a>
        </div>
    </article>
    <a href="#" class="enlace-inferior"><p>Ir arriba</p></a>
    @extends('footer')
</div>
@endsection

resources/views/cart.blade.php
@extends('master')

@section('title')
Camino Librerías - Carrito
@endsection

@section('content')
<div class="container">
    @extends('header')

    <article class="carrito">
        <h4>Tienes estos artículos en tu carrito de compras:</h4>
        <table class="libros">
            <thead>
                <tr>
                    <th colspan="2">Libro</th>
                    <th>Cantidad</th>
                    <th>Precio</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td id="libro-carrito"><img src="libros/batallasdesierto.png" alt=""></td>
                    <td id="libro-carrito">Las batallas en el desierto</td>
                    <td>1</td>
                    <td>$85.00</td>
                </tr>
                <tr class="efect">
                    <td><img src="libros/personanormal.png" alt=""></td>
                    <td>Persona Normal</td>
                    <td>1</td>
                    <td>$100.00</td>
                </tr>
                <tr class="efect">
                    <td><img src="libros/readyplayerone.png" alt=""></td>
                    <td>Ready Player One</td>
                    <td>1</td>
                    <td>$200.00</td>
                </tr>
            </tbody>
        </table>

        <div class="aviso">
            <h4>Aviso importante:</h4>
            <p>
                Debido a la disponibilidad de nuestros productos
                tu pedido será fraccionado en órdenes más pequeñas.
                Tu pedido podría tardar en llegar más de lo esperado.
            </p>
        </div>

        <form class="payment-form">
            <p>Selecciona un tipo de pago</p>

            <input type="radio" name="payment" id="cheque" value="cheque ">
            <label for="cheque">Cheque</label>
            <input type="radio" name="payment" id="tarjeta" value="tarjeta">
            <label for="tarjeta">Tarjeta</label>

            <p>
                <label for="">Nombre</label>
                <input type="text" name="" id="">
            </p>

            <p>
                <label for="">Número</label>
                <input type="text" name="" id="">
            </p>

            <p>
                <label for="">Fecha de expiración</label>
                <input type="text" name="" id="">
            </p>

            <p>
                <label for="">CVV</label>
                <input type="text" name="" id="">
            </p>

            <label for="shipping">Envío</label>
            <select name="shipping" id="shipping">
                <option>Selecciona una opción</option>
                <option value="DHL">DHL - $80.00</option>
                <option value="UPS">UPS - $120.00</option>
                <option value="Estafeta">Estafeta - $100.00</option>
                <option value="FeDex">FeDex - $90.00</option>
            </select>

            <p>Subtotal: $385.00</p>
            <p>Total (con envío): $385.00</p>

            <button type="submit">Pagar</button>
        </form>
    </article>

    @extends('footer')
</div>
@endsection

resources/views/footer.blade.php
@section('footer')
<footer class="inferior">
        <div class="left">
            <center>
                <a href="index.html">
                    <img src="{{ asset('imagenes/logo.png') }}" alt="logo librería camino">
                </a>
                <a href="" class="enlace-inferior">
                    <p>
                        Condiciones de uso
                    </p>
                </a>
                <a href="" class="enlace-inferior">
                    <p>
                        Aviso de Privacidad
                    </p>
                </a>
            </center>
        </div>
        <div class="right">
            <h4 class="seguir">
                Síguenos en nuestras redes sociales:
            </h4>
            <center>
                <a href=""><img src="{{ asset('imagenes/facebook.png') }}" alt="facebook"></a>
                <a href=""><img src="{{ asset('imagenes/twitter.png') }}" alt="twitter"></a>
                <a href=""><img src="{{ asset('imagenes/instagram.png') }}" alt="instagram"></a>
                <a href=""><img src="{{ asset('imagenes/youtube.png') }}" alt="youtube"></a>
            </center>
        </div>
    </footer>
    @endsection

resources/views/header.blade.php
@section('header')
<header class="superior">
    <div class="logo">
        <img src="{{ asset('imagenes/logo.png') }}" alt="logo librería camino">
    </div>
    <nav class="menu">
        <ul class="opciones">
            <li><a href="{{ route('index') }}">INICIO</a></li>
            <li><a href="{{ route('about') }}">NOSOTROS</a></li>
            <li><a href="{{ url('/books') }}">LIBROS</a></li>
            <li><a href="{{ route('track') }}">RASTREAR PEDIDO</a></li>
            @if(session('is_admin') == 1)
            <li><a href="{{ url('/suppliers') }}"><img src="{{ asset('imagenes/truck.png') }}" alt="supplier icon"></a></li>
            @endif
            @if(session()->has('is_admin'))
            <li><a href="{{ route('cart') }}"><img src="{{ asset('imagenes/cart.png') }}" alt="cart icon"></a></li>
            @endif
            <li><a href="{{ route('users.index') }}"><img src="{{ asset('imagenes/user.png') }}" alt="user icon"></a></li>
        </ul>
    </nav>
</header>
@endsection

resources/views/index.blade.php
@extends('master')

@section('title')
Camino Librerías
@endsection

@section('content')
<div class="container">
    @extends('header')
    <section class="slider">
        <img src="imagenes/mainpage.jpg" alt="" width="100%" height="500px">
    </section>

    <section class="best-sellers">
        <h2>¡Estos son los mejores libros de la semana!</h2>
        <article class="book">
            <div class="book-info">
                <a href="">
                    <img src="libros/readyplayerone.png" alt="libro ready player one">
                </a>
                <p>Ready Player One</p>
                <p>Ernest Cline</p>
                <button class="book-button">
                    Ver Libro
                </button>
            </div>
        </article>
        <article class="book">
            <a href="">
                <img src="libros/batallasdesierto.png" alt="libro pedro paramo">
            </a>
            <div class="book-info">
                <p>Las Batallas en el Desierto</p>
                <p>José Emilio Pacheco</p>
                <button class="book-button">
                    Ver Libro
                </button>
            </div>
        </article>
        <article class="book">
            <a href="">
                <img src="libros/pedroparamo.png" alt="libro pedro paramo">
            </a>
            <div class="book-info">
                <p>Pedro Páramo</p>
                <p>Juan Rulfo</p>
                <button class="book-button">
                    Ver Libro
                </button>
            </div>
        </article>
    </section>

    <section class="cuerpo">
        <h1 class="titulo">
            De camino al conocimiento
        </h1>

        <article class="caja">
            <div class="subtitulo">
                <img src="imagenes/catalogue.jpg" alt="">
                <h3 class="servicios">Amplio Catálogo</h3>
            </div>
            <div class="contenido">
                Tenemos el catálogo más amplio del mercado.
                Encuentra tu libro favorito,
                desde literatura clásica hasta libros académicos.
                !Tenemos el libro indicado para ti!.
            </div>
        </article>

        <article class="caja">
            <div class="subtitulo">
                <img src="imagenes/delivery.jpg" alt="">
                <h3 class="servicios">Entregas Rápidas</h3>
            </div>
            <div class="contenido">
                Realiza tu pedido y recíbelo al día siguiente,
                monitoreando en todo en momento el estatus de tu orden.
            </div>
        </article>

        <article class="caja">
            <div class="subtitulo">
                <img src="imagenes/support.jpg" alt="">
                <h3 class="servicios">Soporte al Cliente</h3>
            </div>
            <div class="contenido">
                Si tienes cualquier duda respecto a nuestra tienda
                o con tu pedido, no dudes en comunicarte con
                nuestro soporte al cliente.
            </div>
        </article>
    </section>
</div>
@extends('footer')
</body>
@endsection

resources/views/login.blade.php
@extends('master')

@section('title')
Camino Librerías - Iniciar Sesión
@endsection

@section('content')
<div class="container">
    @extends('header')

    <center>
        <h3>Inicio de Sesión</h3>
        <article class="login-box">
            <form method="POST" action="{{ route('users.store') }}" class="track-form">
                @csrf
                <label for="username">Nombre de usuario:</label>
                <input type="text" name="username" id="username" placeholder="Ingresa tu nombre de usuario">
                <label for="password">Contraseña:</label>
                <input type="password" name="password" id="password">
                <input type="hidden" name="login" value="log">
                <button type="submit">Iniciar Sesión</button>
            </form>
            <p>¿No tienes una cuenta? <a href="{{ route('users.create') }}">¡Crea una!</a></p>
        </article>
    </center>
        
    @extends('footer')
</div>
@endsection

resources/views/master.blade.php
<!DOCTYPE html>

<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title')</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>

<body>
    @yield('header')
    @yield('content')
    @yield('footer')
</body>

</html>

resources/views/register.blade.php
@extends('master')

@section('title')
Camino Librerías - Iniciar Sesión
@endsection

@section('content')
<div class="container">
    @extends('header')

    <center>
        <h3>Registra una cuenta</h3>
        <article class="login-box">
            <form method="POST" action="{{ route('users.store') }}" class="track-form">
                @csrf
                <label for="username">Nombre de usuario:</label>
                <input type="text" name="username" id="username" placeholder="Ingresa tu nombre de usuario">
                <label for="password">Contraseña:</label>
                <input type="password" name="password" id="password">
                <button type="submit">Crear cuenta</button>
            </form>
            <p>¿Ya tienes una cuenta? <a href="{{ route('users.index') }}">¡Inicia sesión!</a></p>
        </article>
    </center>
        
    @extends('footer')
</div>
@endsection

resources/views/suppliers.blade.php
@extends('master')

@section('title')
Camino Librerías - Proovedores
@endsection

@section('content')
<div class="container">
    @extends('header')

    <article class="supplier-history">
        <h4>Historial de compras a proveedores</h4>
        <table class="libros">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Proveedor</th>
                    <th>Fecha</th>
                    <th>Total</th>
                    <th>Estatus</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Editorial Planeta México</td>
                    <td>01/10/2021</td>
                    <td>$5,000.00</td>
                    <td>
                        <p class="enviado">Pagado</p>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Era</td>
                    <td>05/10/2021</td>
                    <td>$2,500.00</td>
                    <td>
                        <p class="pendiente">Pendiente</p>
                    </td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Porrúa</td>
                    <td>08/10/2021</td>
                    <td>$8,750.00</td>
                    <td>
                        <p class="enviado">Pagado</p>
                    </td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Planeta</td>
                    <td>09/10/2021</td>
                    <td>$12,500.00</td>
                    <td>
                        <p class="enviado">Pagado</p>
                    </td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>Era</td>
                    <td>11/10/2021</td>
                    <td>$9,000.00</td>
                    <td>
                        <p class="enviado">Pagado</p>
                    </td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>Porrúa</td>
                    <td>16/10/2021</td>
                    <td>$15,000.00</td>
                    <td>
                        <p class="cancelado">Cancelado</p>
                    </td>
                </tr>
            </tbody>
        </table>
    </article>

    @extends('footer')
</div>
@endsection

resources/views/track.blade.php
@extends('master')

@section('title')
Camino Librerías - Rastrear Pedido
@endsection

@section('content')
<div class="container">
    @extends('header')

    <section class="slider">
        <img src="imagenes/trackpage.jpg" alt="" width="100%" height="500px">
    </section>

    <center>
        <article class="track-box">
            <form action="" class="track-form">
                <label for="trackid">Rastrea tu pedido</label>
                <input type="text" name="trackid" id="trackid" placeholder="Ingresa el ID de tu pedido">
                <button type="submit">Rastrear</button>
            </form>
        </article>
    </center>

    @extends('footer')
</div>
@endsection

resources/views/user.blade.php
@extends('master')

@section('title')
Camino Librerías - Perfil
@endsection

@section('content')
<div class="container">
    @extends('header')

    <article class="user-history">
        <a href="{{ route('users.logout') }}"><h1 class="enlace-inferior">Salir</h1></a>
        <h4>Historial de compras del usuario</h4>
        <table class="libros">
            <thead>
                <tr>
                    <th>#</th>
                    <th>ID Pedido</th>
                    <th>Estatus</th>
                    <th>Total</th>
                    <th>Fecha</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>CL16485</td>
                    <td>
                        <p class="pendiente">Pendiente</p>
                    </td>
                    <td>$380.00</td>
                    <td>Hoy</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>CL91548</td>
                    <td>
                        <p class="pendiente">Pendiente</p>
                    </td>
                    <td>$475.00</td>
                    <td>Ayer</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>CL98742</td>
                    <td>
                        <p class="enviado">Enviado</p>
                    </td>
                    <td>$170.00</td>
                    <td>08/10/2021</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>CL34815</td>
                    <td>
                        <p class="cancelado">Cancelado</p>
                    </td>
                    <td>$275.00</td>
                    <td>15/09/2021</td>
                </tr>
            </tbody>
        </table>
    </article>

    <article>
        <h4>Basado en tus compras, te recomendamos...</h4>
        <article class="book">
            <div class="book-info">
                <a href="">
                    <img src="libros/readyplayerone.png" alt="libro ready player one">
                </a>
                <p>Ready Player One</p>
                <p>Ernest Cline</p>
                <button class="book-button">
                    Ver Libro
                </button>
            </div>
        </article>
        <article class="book">
            <a href="">
                <img src="libros/batallasdesierto.png" alt="libro pedro paramo">
            </a>
            <div class="book-info">
                <p>Las Batallas en el Desierto</p>
                <p>José Emilio Pacheco</p>
                <button class="book-button">
                    Ver Libro
                </button>
            </div>
        </article>
        <article class="book">
            <a href="">
                <img src="libros/pedroparamo.png" alt="libro pedro paramo">
            </a>
            <div class="book-info">
                <p>Pedro Páramo</p>
                <p>Juan Rulfo</p>
                <button class="book-button">
                    Ver Libro
                </button>
            </div>
        </article>
        <p>¡Explora los títulos recomendados para ti!</p>
    </article>
    @extends('footer')
</div>
@endsection